[package]
name = "raydium-clmm-cpi"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-gen = "0.4.0"
anchor-lang = "0.31.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "raydium_clmm_cpi"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
